export const constantsCourseDetalies={
    START_GET_COURSE_DETALIES:"START_GET_COURSE_DETALIES",
    SUCCESS_GET_COURSE_DETALIES:"SUCCESS_GET_COURSE_DETALIES",
    FAIL_GET_COURSE_DETALIES:"FAIL_GET_COURSE_DETALIES"
}